use [Projekt_zespolowy];

SET IDENTITY_INSERT authors ON
INSERT INTO authors (AuthorId, Author) VALUES (1,'Wacław Berent');
INSERT INTO authors (AuthorId, Author) VALUES (2,'Tadeusz Boy-Żeleński');
INSERT INTO authors (AuthorId, Author) VALUES (3,'Tadeusz Borowski');
INSERT INTO authors (AuthorId, Author) VALUES (4,'Radosław Wiśniewski');
INSERT INTO authors (AuthorId, Author) VALUES (5,'Szolem-Alejchem');
INSERT INTO authors (AuthorId, Author) VALUES (6,'Francis Vielé-Griffin');
INSERT INTO authors (AuthorId, Author) VALUES (7,'Stanisław Ignacy Witkiewicz (Witkacy)');
INSERT INTO authors (AuthorId, Author) VALUES (8,'Maria Rodziewiczówna');
INSERT INTO authors (AuthorId, Author) VALUES (9,'Adolf Abrahamowicz');
INSERT INTO authors (AuthorId, Author) VALUES (10,'Niccolo Machiavelli');
INSERT INTO authors (AuthorId, Author) VALUES (11,'Kazimierz Wyka');
INSERT INTO authors (AuthorId, Author) VALUES (12,'Kazimierz Przerwa-Tetmajer');
INSERT INTO authors (AuthorId, Author) VALUES (13,'Karl Arnold Kortum');
INSERT INTO authors (AuthorId, Author) VALUES (14,'Tytus Czyżewski');
INSERT INTO authors (AuthorId, Author) VALUES (15,'Adolf Dygasiński');
INSERT INTO authors (AuthorId, Author) VALUES (16,'Karol Maliszewski');
INSERT INTO authors (AuthorId, Author) VALUES (17,'Maria Skłodowska-Curie');
INSERT INTO authors (AuthorId, Author) VALUES (18,'Heinrich von Kleist');
INSERT INTO authors (AuthorId, Author) VALUES (19,'Marceli Skałkowski');
INSERT INTO authors (AuthorId, Author) VALUES (20,'Hugo von Hofmannsthal');
INSERT INTO authors (AuthorId, Author) VALUES (21,'Théodore de Banville');
INSERT INTO authors (AuthorId, Author) VALUES (22,'Zgromadzenie Ogólne ONZ');
INSERT INTO authors (AuthorId, Author) VALUES (23,'Ludwik Ksawery Pomian-Łubiński');
INSERT INTO authors (AuthorId, Author) VALUES (24,'Halina Krahelska');
INSERT INTO authors (AuthorId, Author) VALUES (25,'Torquato Tasso');
INSERT INTO authors (AuthorId, Author) VALUES (26,'François-René de Chateaubriand');
INSERT INTO authors (AuthorId, Author) VALUES (27,'Szczepan Kopyt');
INSERT INTO authors (AuthorId, Author) VALUES (28,'Gustaw Flaubert');
INSERT INTO authors (AuthorId, Author) VALUES (29,'Justyna Radczyńska-Misiurewicz');
INSERT INTO authors (AuthorId, Author) VALUES (30,'Karol Bołoz Antoniewicz');
INSERT INTO authors (AuthorId, Author) VALUES (31,'Anna Chuda');
INSERT INTO authors (AuthorId, Author) VALUES (32,'Mikołaj Rej');
INSERT INTO authors (AuthorId, Author) VALUES (33,'Michał Bałucki');
INSERT INTO authors (AuthorId, Author) VALUES (34,'Władysław Łoziński');
INSERT INTO authors (AuthorId, Author) VALUES (35,'Bolesław Miciński');
INSERT INTO authors (AuthorId, Author) VALUES (36,'Vincas Pietaris');
INSERT INTO authors (AuthorId, Author) VALUES (37,'Stefania Buda');
INSERT INTO authors (AuthorId, Author) VALUES (38,'Wiktor Teofil Gomulicki');
INSERT INTO authors (AuthorId, Author) VALUES (39,'Mariusz Grzebalski');
INSERT INTO authors (AuthorId, Author) VALUES (40,'Alexander von Humboldt');
INSERT INTO authors (AuthorId, Author) VALUES (41,'Mendele Mojcher-Sforim');
INSERT INTO authors (AuthorId, Author) VALUES (42,'Wacław Potocki');
INSERT INTO authors (AuthorId, Author) VALUES (43,'Ferdynand Ossendowski');
INSERT INTO authors (AuthorId, Author) VALUES (44,'Henryk Sienkiewicz');
INSERT INTO authors (AuthorId, Author) VALUES (45,'Gabriela Zapolska');
INSERT INTO authors (AuthorId, Author) VALUES (46,'August von Platen');
INSERT INTO authors (AuthorId, Author) VALUES (47,'Joachim Gasquet');
INSERT INTO authors (AuthorId, Author) VALUES (48,'Julius Hart');
INSERT INTO authors (AuthorId, Author) VALUES (49,'Franciszek Karpiński');
INSERT INTO authors (AuthorId, Author) VALUES (50,'Stefan George');
INSERT INTO authors (AuthorId, Author) VALUES (51,'Zośka Papużanka');
INSERT INTO authors (AuthorId, Author) VALUES (52,'Émile Verhaeren');
INSERT INTO authors (AuthorId, Author) VALUES (53,'Władysław Stanisław Reymont');
INSERT INTO authors (AuthorId, Author) VALUES (54,'Björnstjerne Björnson');
INSERT INTO authors (AuthorId, Author) VALUES (55,'Teodor Tripplin');
INSERT INTO authors (AuthorId, Author) VALUES (56,'Władysław Bukowiński');
INSERT INTO authors (AuthorId, Author) VALUES (57,'Jacek Podsiadło');
INSERT INTO authors (AuthorId, Author) VALUES (58,'Zofia Rogoszówna');
INSERT INTO authors (AuthorId, Author) VALUES (59,'Wojciech Brzoska');
INSERT INTO authors (AuthorId, Author) VALUES (60,'Zofia Żurakowska');
INSERT INTO authors (AuthorId, Author) VALUES (61,'Pjotr Janicki');
INSERT INTO authors (AuthorId, Author) VALUES (62,'Michał Matys');
INSERT INTO authors (AuthorId, Author) VALUES (63,'Artur Oppman');
INSERT INTO authors (AuthorId, Author) VALUES (64,'Edgar Wallace');
INSERT INTO authors (AuthorId, Author) VALUES (65,'Maria Pawlikowska-Jasnorzewska');
INSERT INTO authors (AuthorId, Author) VALUES (66,'Jan Andrzej Morsztyn');
INSERT INTO authors (AuthorId, Author) VALUES (67,'Frances Hodgson Burnett');
INSERT INTO authors (AuthorId, Author) VALUES (68,'Tadeusz Hollender');
INSERT INTO authors (AuthorId, Author) VALUES (69,'Guy de Maupassant');
INSERT INTO authors (AuthorId, Author) VALUES (70,'Mikołaj Sęp Szarzyński');
INSERT INTO authors (AuthorId, Author) VALUES (71,'Karol Darwin');
INSERT INTO authors (AuthorId, Author) VALUES (72,'Edward Słoński');
INSERT INTO authors (AuthorId, Author) VALUES (73,'Artur Schopenhauer');
INSERT INTO authors (AuthorId, Author) VALUES (74,'Maciej Szukiewicz');
INSERT INTO authors (AuthorId, Author) VALUES (75,'Alojzy Feliński');
INSERT INTO authors (AuthorId, Author) VALUES (76,'Fagus');
INSERT INTO authors (AuthorId, Author) VALUES (77,'Stefan Leszno');
INSERT INTO authors (AuthorId, Author) VALUES (78,'Johann Wolfgang von Goethe');
INSERT INTO authors (AuthorId, Author) VALUES (79,'George Gordon Byron');
INSERT INTO authors (AuthorId, Author) VALUES (80,'E. T. A. Hoffmann');
INSERT INTO authors (AuthorId, Author) VALUES (81,'Prosper Mérimée');
INSERT INTO authors (AuthorId, Author) VALUES (82,'Bolesław Prus');
INSERT INTO authors (AuthorId, Author) VALUES (83,'Andrzej Niemojewski');
INSERT INTO authors (AuthorId, Author) VALUES (84,'Franciszek Mirandola');
INSERT INTO authors (AuthorId, Author) VALUES (85,'Bronisława Ostrowska');
INSERT INTO authors (AuthorId, Author) VALUES (86,'Władysław Bełza');
INSERT INTO authors (AuthorId, Author) VALUES (87,'Daniel Defoe');
INSERT INTO authors (AuthorId, Author) VALUES (88,'Seweryn Goszczyński');
INSERT INTO authors (AuthorId, Author) VALUES (89,'Pierre Choderlos de Laclos');
INSERT INTO authors (AuthorId, Author) VALUES (90,'Józef Wybicki');
INSERT INTO authors (AuthorId, Author) VALUES (91,'Julien Offray de La Mettrie');
INSERT INTO authors (AuthorId, Author) VALUES (92,'Edith Nesbit');
INSERT INTO authors (AuthorId, Author) VALUES (93,'Marcin Sendecki');
INSERT INTO authors (AuthorId, Author) VALUES (94,'Maria Konopnicka');
INSERT INTO authors (AuthorId, Author) VALUES (95,'Radek Rak');
INSERT INTO authors (AuthorId, Author) VALUES (96,'Gustaw Daniłowski');
INSERT INTO authors (AuthorId, Author) VALUES (97,'Marcel Proust');
INSERT INTO authors (AuthorId, Author) VALUES (98,'Karol Marks');
INSERT INTO authors (AuthorId, Author) VALUES (99,'Stanisław Wyspiański');
INSERT INTO authors (AuthorId, Author) VALUES (100,'Maria Cyranowicz');
INSERT INTO authors (AuthorId, Author) VALUES (101,'Gustave Kahn');
INSERT INTO authors (AuthorId, Author) VALUES (102,'Antoni Malczewski');
INSERT INTO authors (AuthorId, Author) VALUES (103,'Eugeniusz Tkaczyszyn-Dycki');
INSERT INTO authors (AuthorId, Author) VALUES (104,'Max Dauthendey');
INSERT INTO authors (AuthorId, Author) VALUES (105,'Aloysius Bertrand');
INSERT INTO authors (AuthorId, Author) VALUES (106,'Henryk Rzewuski');
INSERT INTO authors (AuthorId, Author) VALUES (107,'Demostenes');
INSERT INTO authors (AuthorId, Author) VALUES (108,'Patrycja Nowak');
INSERT INTO authors (AuthorId, Author) VALUES (109,'Darek Foks');
INSERT INTO authors (AuthorId, Author) VALUES (110,'Urke Nachalnik');
INSERT INTO authors (AuthorId, Author) VALUES (111,'Alter Kacyzne');
INSERT INTO authors (AuthorId, Author) VALUES (112,'Cezary Jellenta');
INSERT INTO authors (AuthorId, Author) VALUES (113,'Antonina Domańska');
INSERT INTO authors (AuthorId, Author) VALUES (114,'Maciej Stryjkowski');
INSERT INTO authors (AuthorId, Author) VALUES (115,'Charles Cros');
INSERT INTO authors (AuthorId, Author) VALUES (116,'Theodor Däubler');
INSERT INTO authors (AuthorId, Author) VALUES (117,'Žemaitė');
INSERT INTO authors (AuthorId, Author) VALUES (118,'Paweł Beręsewicz');
INSERT INTO authors (AuthorId, Author) VALUES (119,'Jean-Marc Bernard');
INSERT INTO authors (AuthorId, Author) VALUES (120,'Max Elskamp');
INSERT INTO authors (AuthorId, Author) VALUES (121,'Motiejus Valančius');
INSERT INTO authors (AuthorId, Author) VALUES (122,'Wojciech B. Mencel');
INSERT INTO authors (AuthorId, Author) VALUES (123,'Franciszek Kowalski');
INSERT INTO authors (AuthorId, Author) VALUES (124,'Stanisław Brzozowski');
INSERT INTO authors (AuthorId, Author) VALUES (125,'Jan Sten');
INSERT INTO authors (AuthorId, Author) VALUES (126,'Anna Cieśla');
INSERT INTO authors (AuthorId, Author) VALUES (127,'Władysław Grabski');
INSERT INTO authors (AuthorId, Author) VALUES (128,'Carl Spitteler');
INSERT INTO authors (AuthorId, Author) VALUES (129,'Andrzej Kijowski');
INSERT INTO authors (AuthorId, Author) VALUES (130,'Rodrigues Ottolengui');
INSERT INTO authors (AuthorId, Author) VALUES (131,'Andrzej Trzebiński');
INSERT INTO authors (AuthorId, Author) VALUES (132,'Emil Zola');
INSERT INTO authors (AuthorId, Author) VALUES (133,'Zdzisław Dębicki');
INSERT INTO authors (AuthorId, Author) VALUES (134,'Deotyma');
INSERT INTO authors (AuthorId, Author) VALUES (135,'Charles Van Lerberghe');
INSERT INTO authors (AuthorId, Author) VALUES (136,'Edward Redliński');
INSERT INTO authors (AuthorId, Author) VALUES (137,'Bruno Schulz');
INSERT INTO authors (AuthorId, Author) VALUES (138,'Stanisław Witkiewicz');
INSERT INTO authors (AuthorId, Author) VALUES (139,'Barbara Klicka');
INSERT INTO authors (AuthorId, Author) VALUES (140,'Oliver Goldsmith');
INSERT INTO authors (AuthorId, Author) VALUES (141,'Anna Libera (Anna Krakowianka)');
INSERT INTO authors (AuthorId, Author) VALUES (142,'Stendhal');
INSERT INTO authors (AuthorId, Author) VALUES (143,'Magdalena Tulli');
INSERT INTO authors (AuthorId, Author) VALUES (144,'Eliza Orzeszkowa');
INSERT INTO authors (AuthorId, Author) VALUES (145,'Zofia Wydro');
INSERT INTO authors (AuthorId, Author) VALUES (146,'Robert Louis Stevenson');
INSERT INTO authors (AuthorId, Author) VALUES (147,'Bogdan Wojdowski');
INSERT INTO authors (AuthorId, Author) VALUES (148,'Jerzy Kamil Weintraub-Krzyżanowski');
INSERT INTO authors (AuthorId, Author) VALUES (149,'Owidiusz');
INSERT INTO authors (AuthorId, Author) VALUES (150,'Włodzimierz Perzyński');
INSERT INTO authors (AuthorId, Author) VALUES (151,'Rudyard Kipling');
INSERT INTO authors (AuthorId, Author) VALUES (152,'Konrad Gliściński');
INSERT INTO authors (AuthorId, Author) VALUES (153,'Agnieszka Wolny-Hamkało');
INSERT INTO authors (AuthorId, Author) VALUES (154,'Guido Gozzano');
INSERT INTO authors (AuthorId, Author) VALUES (155,'Giovanni Boccaccio');
INSERT INTO authors (AuthorId, Author) VALUES (156,'Ludovico Ariosto');
INSERT INTO authors (AuthorId, Author) VALUES (157,'Paulina Kuczalska-Reinschmit');
INSERT INTO authors (AuthorId, Author) VALUES (158,'Eleonora Kalkowska');
INSERT INTO authors (AuthorId, Author) VALUES (159,'Ignacy Dąbrowski');
INSERT INTO authors (AuthorId, Author) VALUES (160,'Alfred de Musset');
INSERT INTO authors (AuthorId, Author) VALUES (161,'Zygmunt Kaczkowski');
INSERT INTO authors (AuthorId, Author) VALUES (162,'Karl Gjellerup');
INSERT INTO authors (AuthorId, Author) VALUES (163,'Gerhart Hauptmann');
INSERT INTO authors (AuthorId, Author) VALUES (164,'Safona');
INSERT INTO authors (AuthorId, Author) VALUES (165,'Antanas Baranauskas');
INSERT INTO authors (AuthorId, Author) VALUES (166,'Jan Kochanowski');
INSERT INTO authors (AuthorId, Author) VALUES (167,'Władysław Witwicki');
INSERT INTO authors (AuthorId, Author) VALUES (168,'Jacob i Wilhelm Grimm');
INSERT INTO authors (AuthorId, Author) VALUES (169,'Tadeusz Gajcy');
INSERT INTO authors (AuthorId, Author) VALUES (170,'Julian Kornhauser');
INSERT INTO authors (AuthorId, Author) VALUES (171,'Plaut');
INSERT INTO authors (AuthorId, Author) VALUES (172,'Dzierżek');
INSERT INTO authors (AuthorId, Author) VALUES (173,'Maurice Leblanc');
INSERT INTO authors (AuthorId, Author) VALUES (174,'Teresa Bogusławska');
INSERT INTO authors (AuthorId, Author) VALUES (175,'Krystyna Miłobędzka');
INSERT INTO authors (AuthorId, Author) VALUES (176,'René Descartes (Kartezjusz)');
INSERT INTO authors (AuthorId, Author) VALUES (177,'Arystofanes');
INSERT INTO authors (AuthorId, Author) VALUES (178,'Fryderyk Schiller');
INSERT INTO authors (AuthorId, Author) VALUES (179,'Charles Dickens');
INSERT INTO authors (AuthorId, Author) VALUES (180,'Marek Aureliusz');
INSERT INTO authors (AuthorId, Author) VALUES (181,'Feliks Brodowski');
INSERT INTO authors (AuthorId, Author) VALUES (182,'Wioletta Grzegorzewska');
INSERT INTO authors (AuthorId, Author) VALUES (183,'Wiktor Czermak');
INSERT INTO authors (AuthorId, Author) VALUES (184,'Aleksander Świętochowski');
INSERT INTO authors (AuthorId, Author) VALUES (185,'Subcomandante Marcos');
INSERT INTO authors (AuthorId, Author) VALUES (186,'Oscar Wilde');
INSERT INTO authors (AuthorId, Author) VALUES (187,'Daniel Naborowski');
INSERT INTO authors (AuthorId, Author) VALUES (188,'Bożena Keff');
INSERT INTO authors (AuthorId, Author) VALUES (189,'Hugh Lofting');
INSERT INTO authors (AuthorId, Author) VALUES (190,'Jan Słomka');
INSERT INTO authors (AuthorId, Author) VALUES (191,'Julian Ursyn Niemcewicz');
INSERT INTO authors (AuthorId, Author) VALUES (192,'Anton Czechow');
INSERT INTO authors (AuthorId, Author) VALUES (193,'Konstanty Gaszyński');
INSERT INTO authors (AuthorId, Author) VALUES (194,'Detlev von Liliencron');
INSERT INTO authors (AuthorId, Author) VALUES (195,'Pierre de Marivaux');
INSERT INTO authors (AuthorId, Author) VALUES (196,'Miłosz Biedrzycki');
INSERT INTO authors (AuthorId, Author) VALUES (197,'Denis Diderot');
INSERT INTO authors (AuthorId, Author) VALUES (198,'Bolesław Piach');
INSERT INTO authors (AuthorId, Author) VALUES (199,'Wacław Święcicki');
INSERT INTO authors (AuthorId, Author) VALUES (200,'Autor nieznany');
INSERT INTO authors (AuthorId, Author) VALUES (201,'Bianka Rolando');
INSERT INTO authors (AuthorId, Author) VALUES (202,'Jonas Biliūnas');
INSERT INTO authors (AuthorId, Author) VALUES (203,'Louis Gallet');
INSERT INTO authors (AuthorId, Author) VALUES (204,'Mieczysław Braun');
INSERT INTO authors (AuthorId, Author) VALUES (205,'Fryderyk Hölderlin');
INSERT INTO authors (AuthorId, Author) VALUES (206,'Saint-Pol-Roux');
INSERT INTO authors (AuthorId, Author) VALUES (207,'Aleksander Brückner');
INSERT INTO authors (AuthorId, Author) VALUES (208,'Zuzanna Morawska');
INSERT INTO authors (AuthorId, Author) VALUES (209,'Arthur Conan Doyle');
INSERT INTO authors (AuthorId, Author) VALUES (210,'Henryk Ibsen');
INSERT INTO authors (AuthorId, Author) VALUES (211,'Władysław Tarnowski');
INSERT INTO authors (AuthorId, Author) VALUES (212,'Edmond Rostand');
INSERT INTO authors (AuthorId, Author) VALUES (213,'Wacław Bojarski');
INSERT INTO authors (AuthorId, Author) VALUES (214,'Józef Ignacy Kraszewski');
INSERT INTO authors (AuthorId, Author) VALUES (215,'Wacław Rolicz-Lieder');
INSERT INTO authors (AuthorId, Author) VALUES (216,'Anatole Le Braz');
INSERT INTO authors (AuthorId, Author) VALUES (217,'Maurice Maeterlinck');
INSERT INTO authors (AuthorId, Author) VALUES (218,'Aleksander Dumas (syn)');
INSERT INTO authors (AuthorId, Author) VALUES (219,'Kazimierz Morawski');
INSERT INTO authors (AuthorId, Author) VALUES (220,'Paul Heyse');
INSERT INTO authors (AuthorId, Author) VALUES (221,'Christof Schmid');
INSERT INTO authors (AuthorId, Author) VALUES (222,'Wacław Wolski');
INSERT INTO authors (AuthorId, Author) VALUES (223,'Zofia Urbanowska');
INSERT INTO authors (AuthorId, Author) VALUES (224,'Françoise de Graffigny');
INSERT INTO authors (AuthorId, Author) VALUES (225,'Sz. An-ski');
INSERT INTO authors (AuthorId, Author) VALUES (226,'Maria Ratuld-Rakowska');
INSERT INTO authors (AuthorId, Author) VALUES (227,'Jonathan Swift');
INSERT INTO authors (AuthorId, Author) VALUES (228,'Julia Duszyńska');
INSERT INTO authors (AuthorId, Author) VALUES (229,'Jerzy Liebert');
INSERT INTO authors (AuthorId, Author) VALUES (230,'Antoni Sobański');
INSERT INTO authors (AuthorId, Author) VALUES (231,'Lucjan Rydel');
INSERT INTO authors (AuthorId, Author) VALUES (232,'Alfred Jarry');
INSERT INTO authors (AuthorId, Author) VALUES (233,'Józef Birkenmajer');
INSERT INTO authors (AuthorId, Author) VALUES (234,'Cyprian Kamil Norwid');
INSERT INTO authors (AuthorId, Author) VALUES (235,'Zygmunt Krasiński');
INSERT INTO authors (AuthorId, Author) VALUES (236,'Ellen Key');
INSERT INTO authors (AuthorId, Author) VALUES (237,'Wincenty Pol');
INSERT INTO authors (AuthorId, Author) VALUES (238,'Felicjan Faleński');
INSERT INTO authors (AuthorId, Author) VALUES (239,'Rainer Maria Rilke');
INSERT INTO authors (AuthorId, Author) VALUES (240,'Anatole France');
INSERT INTO authors (AuthorId, Author) VALUES (241,'Adam Kaczanowski');
INSERT INTO authors (AuthorId, Author) VALUES (242,'Roman Dyboski');
INSERT INTO authors (AuthorId, Author) VALUES (243,'Gustav Meyrink');
INSERT INTO authors (AuthorId, Author) VALUES (244,'Stanisław Trembecki');
INSERT INTO authors (AuthorId, Author) VALUES (245,'Józef Bliziński');
INSERT INTO authors (AuthorId, Author) VALUES (246,'Lucy Maud Montgomery');
INSERT INTO authors (AuthorId, Author) VALUES (247,'Aleksander Dumas (ojciec)');
INSERT INTO authors (AuthorId, Author) VALUES (248,'Pietro Aretino');
INSERT INTO authors (AuthorId, Author) VALUES (249,'Ignacy Krasicki');
INSERT INTO authors (AuthorId, Author) VALUES (250,'August Bielowski');
INSERT INTO authors (AuthorId, Author) VALUES (251,'Olympe Audouard');
INSERT INTO authors (AuthorId, Author) VALUES (252,'Krzysztof Kamil Baczyński');
INSERT INTO authors (AuthorId, Author) VALUES (253,'Friedrich Nietzsche');
INSERT INTO authors (AuthorId, Author) VALUES (254,'Maurycy Schlanger');
INSERT INTO authors (AuthorId, Author) VALUES (255,'Narcyza Żmichowska');
INSERT INTO authors (AuthorId, Author) VALUES (256,'Józef Szczepański');
INSERT INTO authors (AuthorId, Author) VALUES (257,'Jaroslav Hašek');
INSERT INTO authors (AuthorId, Author) VALUES (258,'Piotr Skarga');
INSERT INTO authors (AuthorId, Author) VALUES (259,'Andrzej Frycz Modrzewski');
INSERT INTO authors (AuthorId, Author) VALUES (260,'Stefan Grabiński');
INSERT INTO authors (AuthorId, Author) VALUES (261,'Herbert George Wells');
INSERT INTO authors (AuthorId, Author) VALUES (262,'Sébastien-Roch Nicolas de Chamfort');
INSERT INTO authors (AuthorId, Author) VALUES (263,'Charles Guérin');
INSERT INTO authors (AuthorId, Author) VALUES (264,'Wincenty Korab-Brzozowski');
INSERT INTO authors (AuthorId, Author) VALUES (265,'Karol Libelt');
INSERT INTO authors (AuthorId, Author) VALUES (266,'Albert Samain');
INSERT INTO authors (AuthorId, Author) VALUES (267,'Agnieszka Frączek');
INSERT INTO authors (AuthorId, Author) VALUES (268,'Karel Čapek');
INSERT INTO authors (AuthorId, Author) VALUES (269,'Tadeusz Nalepiński');
INSERT INTO authors (AuthorId, Author) VALUES (270,'Benedykt de Spinoza');
INSERT INTO authors (AuthorId, Author) VALUES (271,'Tadeusz Dołęga-Mostowicz');
INSERT INTO authors (AuthorId, Author) VALUES (272,'Léon Deubel');
INSERT INTO authors (AuthorId, Author) VALUES (273,'Jan Grabowski');
INSERT INTO authors (AuthorId, Author) VALUES (274,'Henry Bataille');
INSERT INTO authors (AuthorId, Author) VALUES (275,'Liudvika Didžiulienė-Žmona');
INSERT INTO authors (AuthorId, Author) VALUES (276,'Sylwia Chutnik');
INSERT INTO authors (AuthorId, Author) VALUES (277,'Artur Schnitzler');
INSERT INTO authors (AuthorId, Author) VALUES (278,'Gotthold Ephraim Lessing');
INSERT INTO authors (AuthorId, Author) VALUES (279,'Leo Lipski');
INSERT INTO authors (AuthorId, Author) VALUES (280,'Louis le Cardonnel');
INSERT INTO authors (AuthorId, Author) VALUES (281,'Stanisław Staszic');
INSERT INTO authors (AuthorId, Author) VALUES (282,'Julia Fiedorczuk');
INSERT INTO authors (AuthorId, Author) VALUES (283,'Mark Twain');
INSERT INTO authors (AuthorId, Author) VALUES (284,'Søren Kierkegaard');
INSERT INTO authors (AuthorId, Author) VALUES (285,'Icchok Lejb Perec');
INSERT INTO authors (AuthorId, Author) VALUES (286,'Jules Gabriel Verne');
INSERT INTO authors (AuthorId, Author) VALUES (287,'Eurypides');
INSERT INTO authors (AuthorId, Author) VALUES (288,'Joanna Papuzińska');
INSERT INTO authors (AuthorId, Author) VALUES (289,'Henri de Régnier');
INSERT INTO authors (AuthorId, Author) VALUES (290,'Maria Dąbrowska');
INSERT INTO authors (AuthorId, Author) VALUES (291,'Jean Richepin');
INSERT INTO authors (AuthorId, Author) VALUES (292,'Stefan Zweig');
INSERT INTO authors (AuthorId, Author) VALUES (293,'Andrzej Sosnowski');
INSERT INTO authors (AuthorId, Author) VALUES (294,'Pierre Corneille');
INSERT INTO authors (AuthorId, Author) VALUES (295,'Jan Chryzostom Pasek');
INSERT INTO authors (AuthorId, Author) VALUES (296,'Wespazjan Hieronim Kochowski');
INSERT INTO authors (AuthorId, Author) VALUES (297,'William Makepeace Thackeray');
INSERT INTO authors (AuthorId, Author) VALUES (298,'Jędrzej Kitowicz');
INSERT INTO authors (AuthorId, Author) VALUES (299,'Molière (Molier)');
INSERT INTO authors (AuthorId, Author) VALUES (300,'Władysław Anczyc');
INSERT INTO authors (AuthorId, Author) VALUES (301,'Juliusz Słowacki');
INSERT INTO authors (AuthorId, Author) VALUES (302,'Dōgen Kigen');
INSERT INTO authors (AuthorId, Author) VALUES (303,'Juliusz Krzyżewski');
INSERT INTO authors (AuthorId, Author) VALUES (304,'Otto Weininger');
INSERT INTO authors (AuthorId, Author) VALUES (305,'Aleksander Puszkin');
INSERT INTO authors (AuthorId, Author) VALUES (306,'Johanna Spyri');
INSERT INTO authors (AuthorId, Author) VALUES (307,'Kazimierz Deczyński');
INSERT INTO authors (AuthorId, Author) VALUES (308,'Krystyna Krahelska');
INSERT INTO authors (AuthorId, Author) VALUES (309,'Fiodor Dostojewski');
INSERT INTO authors (AuthorId, Author) VALUES (310,'Platon');
INSERT INTO authors (AuthorId, Author) VALUES (311,'Tristan Derème');
INSERT INTO authors (AuthorId, Author) VALUES (312,'Zofia Kucharczyk');
INSERT INTO authors (AuthorId, Author) VALUES (313,'Klemens Junosza');
INSERT INTO authors (AuthorId, Author) VALUES (314,'Marceline Desbordes-Valmore');
INSERT INTO authors (AuthorId, Author) VALUES (315,'Joanna Mueller');
INSERT INTO authors (AuthorId, Author) VALUES (316,'Michalina Domańska');
INSERT INTO authors (AuthorId, Author) VALUES (317,'Edward Pasewicz');
INSERT INTO authors (AuthorId, Author) VALUES (318,'Edmondo de Amicis');
INSERT INTO authors (AuthorId, Author) VALUES (319,'Taras Szewczenko');
INSERT INTO authors (AuthorId, Author) VALUES (320,'Antoni Lange');
INSERT INTO authors (AuthorId, Author) VALUES (321,'Piotr Sommer');
INSERT INTO authors (AuthorId, Author) VALUES (322,'Tytus Chałubiński');
INSERT INTO authors (AuthorId, Author) VALUES (323,'Ludovic Halévy');
INSERT INTO authors (AuthorId, Author) VALUES (324,'Józef Ruffer');
INSERT INTO authors (AuthorId, Author) VALUES (325,'Edward Leszczyński');
INSERT INTO authors (AuthorId, Author) VALUES (326,'Elżbieta Lipińska');
INSERT INTO authors (AuthorId, Author) VALUES (327,'Adam Mickiewicz');
INSERT INTO authors (AuthorId, Author) VALUES (328,'Adam M-ski');
INSERT INTO authors (AuthorId, Author) VALUES (329,'Selma Lagerlöf');
INSERT INTO authors (AuthorId, Author) VALUES (330,'Edgar Allan Poe');
INSERT INTO authors (AuthorId, Author) VALUES (331,'Paweł Sołtys');
INSERT INTO authors (AuthorId, Author) VALUES (332,'Kenneth Grahame');
INSERT INTO authors (AuthorId, Author) VALUES (333,'Mykolas Palionis');
INSERT INTO authors (AuthorId, Author) VALUES (334,'Jan Niecisław Baudouin de Courtenay');
INSERT INTO authors (AuthorId, Author) VALUES (335,'Guillaume Apollinaire');
INSERT INTO authors (AuthorId, Author) VALUES (336,'Szymon Askenazy');
INSERT INTO authors (AuthorId, Author) VALUES (337,'Praca zbiorowa');
INSERT INTO authors (AuthorId, Author) VALUES (338,'Miguel de Cervantes Saavedra');
INSERT INTO authors (AuthorId, Author) VALUES (339,'Stéphane Mallarmé');
INSERT INTO authors (AuthorId, Author) VALUES (340,'Gustaw Ehrenberg');
INSERT INTO authors (AuthorId, Author) VALUES (341,'Halina Górska');
INSERT INTO authors (AuthorId, Author) VALUES (342,'Jerzy Jarniewicz');
INSERT INTO authors (AuthorId, Author) VALUES (343,'Klara Nowakowska');
INSERT INTO authors (AuthorId, Author) VALUES (344,'Pierre Beaumarchais');
INSERT INTO authors (AuthorId, Author) VALUES (345,'Justyna Budzińska-Tylicka');
INSERT INTO authors (AuthorId, Author) VALUES (346,'Max Jacob');
INSERT INTO authors (AuthorId, Author) VALUES (347,'Michaił Bułhakow');
INSERT INTO authors (AuthorId, Author) VALUES (348,'François Rabelais');
INSERT INTO authors (AuthorId, Author) VALUES (349,'Arystoteles');
INSERT INTO authors (AuthorId, Author) VALUES (350,'Maria Grossek-Korycka');
INSERT INTO authors (AuthorId, Author) VALUES (351,'Jerzy Andrzejewski');
INSERT INTO authors (AuthorId, Author) VALUES (352,'Ziemowit Szczerek');
INSERT INTO authors (AuthorId, Author) VALUES (353,'Blaise Pascal');
INSERT INTO authors (AuthorId, Author) VALUES (354,'Zygmunt Miłkowski');
INSERT INTO authors (AuthorId, Author) VALUES (355,'Zbigniew Uniłowski');
INSERT INTO authors (AuthorId, Author) VALUES (356,'Adolphe Retté');
INSERT INTO authors (AuthorId, Author) VALUES (357,'Stanisław Korab-Brzozowski');
INSERT INTO authors (AuthorId, Author) VALUES (358,'Władysław Orkan');
INSERT INTO authors (AuthorId, Author) VALUES (359,'Zgromadzenie Ogólne Ligi Narodów');
INSERT INTO authors (AuthorId, Author) VALUES (360,'Józef Roth');
INSERT INTO authors (AuthorId, Author) VALUES (361,'Henryk Zbierzchowski');
INSERT INTO authors (AuthorId, Author) VALUES (362,'Cecylia Walewska');
INSERT INTO authors (AuthorId, Author) VALUES (363,'Jean Baptiste Racine');
INSERT INTO authors (AuthorId, Author) VALUES (364,'Zdzisław Stroiński');
INSERT INTO authors (AuthorId, Author) VALUES (365,'Dominik Bielicki');
INSERT INTO authors (AuthorId, Author) VALUES (366,'Zygmunt Gloger');
INSERT INTO authors (AuthorId, Author) VALUES (367,'Pierre Louÿs');
INSERT INTO authors (AuthorId, Author) VALUES (368,'Władysław Syrokomla');
INSERT INTO authors (AuthorId, Author) VALUES (369,'Jehoszua Perle');
INSERT INTO authors (AuthorId, Author) VALUES (370,'Šatrijos Ragana');
INSERT INTO authors (AuthorId, Author) VALUES (371,'Rajnold Suchodolski');
INSERT INTO authors (AuthorId, Author) VALUES (372,'Franciszek Nowicki');
INSERT INTO authors (AuthorId, Author) VALUES (373,'Homer');
INSERT INTO authors (AuthorId, Author) VALUES (374,'Hans Christian Andersen');
INSERT INTO authors (AuthorId, Author) VALUES (375,'Horacy');
INSERT INTO authors (AuthorId, Author) VALUES (376,'Jean Moréas');
INSERT INTO authors (AuthorId, Author) VALUES (377,'Francis Jammes');
INSERT INTO authors (AuthorId, Author) VALUES (378,'Adam Asnyk');
INSERT INTO authors (AuthorId, Author) VALUES (379,'Janusz Korczak');
INSERT INTO authors (AuthorId, Author) VALUES (380,'Antoine de Saint-Exupéry');
INSERT INTO authors (AuthorId, Author) VALUES (381,'Marian Zdziechowski');
INSERT INTO authors (AuthorId, Author) VALUES (382,'Charles Baudelaire');
INSERT INTO authors (AuthorId, Author) VALUES (383,'Novalis');
INSERT INTO authors (AuthorId, Author) VALUES (384,'Georges Rodenbach');
INSERT INTO authors (AuthorId, Author) VALUES (385,'Izabela Moszczeńska-Rzepecka');
INSERT INTO authors (AuthorId, Author) VALUES (386,'Voltaire (Wolter)');
INSERT INTO authors (AuthorId, Author) VALUES (387,'Honoré de Balzac');
INSERT INTO authors (AuthorId, Author) VALUES (388,'Maironis');
INSERT INTO authors (AuthorId, Author) VALUES (389,'Justyna Bargielska');
INSERT INTO authors (AuthorId, Author) VALUES (390,'Louisa May Alcott');
INSERT INTO authors (AuthorId, Author) VALUES (391,'Georg Büchner');
INSERT INTO authors (AuthorId, Author) VALUES (392,'Adam Wiedemann');
INSERT INTO authors (AuthorId, Author) VALUES (393,'Zuzanna Ginczanka');
INSERT INTO authors (AuthorId, Author) VALUES (394,'Teofil Lenartowicz');
INSERT INTO authors (AuthorId, Author) VALUES (395,'Stuart Merrill');
INSERT INTO authors (AuthorId, Author) VALUES (396,'Jaś Kapela');
INSERT INTO authors (AuthorId, Author) VALUES (397,'James Oliver Curwood');
INSERT INTO authors (AuthorId, Author) VALUES (398,'Barbara Sroczyńska');
INSERT INTO authors (AuthorId, Author) VALUES (399,'François Villon');
INSERT INTO authors (AuthorId, Author) VALUES (400,'Izaak Babel');
INSERT INTO authors (AuthorId, Author) VALUES (401,'Rabindranath Tagore');
INSERT INTO authors (AuthorId, Author) VALUES (402,'William Butler Yeats');
INSERT INTO authors (AuthorId, Author) VALUES (403,'Jan Vaihinger');
INSERT INTO authors (AuthorId, Author) VALUES (404,'Helena Mniszkówna');
INSERT INTO authors (AuthorId, Author) VALUES (405,'Dante Alighieri');
INSERT INTO authors (AuthorId, Author) VALUES (406,'Sofokles');
INSERT INTO authors (AuthorId, Author) VALUES (407,'Kazimierz Twardowski');
INSERT INTO authors (AuthorId, Author) VALUES (408,'Pedro Calderon de la Barca');
INSERT INTO authors (AuthorId, Author) VALUES (409,'Światopełk Karpiński');
INSERT INTO authors (AuthorId, Author) VALUES (410,'Jean-Jacques Rousseau');
INSERT INTO authors (AuthorId, Author) VALUES (411,'Stefan Witwicki');
INSERT INTO authors (AuthorId, Author) VALUES (412,'William Shakespeare (Szekspir)');
INSERT INTO authors (AuthorId, Author) VALUES (413,'Karol Irzykowski');
INSERT INTO authors (AuthorId, Author) VALUES (414,'Vincas Kudirka');
INSERT INTO authors (AuthorId, Author) VALUES (415,'Jarosław Lipszyc');
INSERT INTO authors (AuthorId, Author) VALUES (416,'Marta Podgórnik');
INSERT INTO authors (AuthorId, Author) VALUES (417,'Bronisław Malinowski');
INSERT INTO authors (AuthorId, Author) VALUES (418,'Stefan Żeromski');
INSERT INTO authors (AuthorId, Author) VALUES (419,'Fryderyk Hebbel');
INSERT INTO authors (AuthorId, Author) VALUES (420,'Emilio Salgari');
INSERT INTO authors (AuthorId, Author) VALUES (421,'Elżbieta Drużbacka');
INSERT INTO authors (AuthorId, Author) VALUES (422,'Giacomo Giovanni Casanova');
INSERT INTO authors (AuthorId, Author) VALUES (423,'Michał Dymitr Krajewski');
INSERT INTO authors (AuthorId, Author) VALUES (424,'Feliks Salten');
INSERT INTO authors (AuthorId, Author) VALUES (425,'Stanisław Przybyszewski');
INSERT INTO authors (AuthorId, Author) VALUES (426,'Kazimiera Zawistowska');
INSERT INTO authors (AuthorId, Author) VALUES (427,'Bruno Winawer');
INSERT INTO authors (AuthorId, Author) VALUES (428,'Olaf Stapledon');
INSERT INTO authors (AuthorId, Author) VALUES (429,'Jan Lemański');
INSERT INTO authors (AuthorId, Author) VALUES (430,'Antanas Kriščiukaitis-Aišbė');
INSERT INTO authors (AuthorId, Author) VALUES (431,'Jan Kasprowicz');
INSERT INTO authors (AuthorId, Author) VALUES (432,'Casimir Delavigne');
INSERT INTO authors (AuthorId, Author) VALUES (433,'Oskar Loerke');
INSERT INTO authors (AuthorId, Author) VALUES (434,'Klementyna z Tańskich Hoffmanowa');
INSERT INTO authors (AuthorId, Author) VALUES (435,'Maksim Gorki');
INSERT INTO authors (AuthorId, Author) VALUES (436,'Ksenofont');
INSERT INTO authors (AuthorId, Author) VALUES (437,'Józef Czechowicz');
INSERT INTO authors (AuthorId, Author) VALUES (438,'Julie de Lespinasse');
INSERT INTO authors (AuthorId, Author) VALUES (439,'Maryla Wolska');
INSERT INTO authors (AuthorId, Author) VALUES (440,'Bolesław Leśmian');
INSERT INTO authors (AuthorId, Author) VALUES (441,'Maria De La Fayette');
INSERT INTO authors (AuthorId, Author) VALUES (442,'Otto zur Linde');
INSERT INTO authors (AuthorId, Author) VALUES (443,'Joseph Mohr');
INSERT INTO authors (AuthorId, Author) VALUES (444,'Ferdinand Avenarius');
INSERT INTO authors (AuthorId, Author) VALUES (445,'Aleksander Fredro');
INSERT INTO authors (AuthorId, Author) VALUES (446,'Tadeusz Miciński');
INSERT INTO authors (AuthorId, Author) VALUES (447,'Helena Janina Pajzderska');
INSERT INTO authors (AuthorId, Author) VALUES (448,'Kazimiera Bujwidowa');
INSERT INTO authors (AuthorId, Author) VALUES (449,'Andrzej Strug');
INSERT INTO authors (AuthorId, Author) VALUES (450,'Czesław Halicz (właśc. Czesława Endelmanowa-Rosenblattowa)');
INSERT INTO authors (AuthorId, Author) VALUES (451,'Artur Gruszecki');
INSERT INTO authors (AuthorId, Author) VALUES (452,'Bruno Jasieński');
INSERT INTO authors (AuthorId, Author) VALUES (453,'Michel de Montaigne');
INSERT INTO authors (AuthorId, Author) VALUES (454,'Władysław Szlengel');
INSERT INTO authors (AuthorId, Author) VALUES (455,'Friedrich Paulsen');
INSERT INTO authors (AuthorId, Author) VALUES (456,'Roman Jaworski');
INSERT INTO authors (AuthorId, Author) VALUES (457,'Paweł Kozioł');
INSERT INTO authors (AuthorId, Author) VALUES (458,'Ksawery Pruszyński');
INSERT INTO authors (AuthorId, Author) VALUES (459,'Edmund Wasilewski');
INSERT INTO authors (AuthorId, Author) VALUES (460,'Wacław Gąsiorowski');
INSERT INTO authors (AuthorId, Author) VALUES (461,'Rudolf G. Binding');
INSERT INTO authors (AuthorId, Author) VALUES (462,'Immanuel Kant');
INSERT INTO authors (AuthorId, Author) VALUES (463,'Zofia Daszyńska-Golińska');
INSERT INTO authors (AuthorId, Author) VALUES (464,'Jerzy Żuławski');
INSERT INTO authors (AuthorId, Author) VALUES (465,'Wincenty Korotyński');
INSERT INTO authors (AuthorId, Author) VALUES (466,'Wergiliusz');
INSERT INTO authors (AuthorId, Author) VALUES (467,'Heinrich Heine');
INSERT INTO authors (AuthorId, Author) VALUES (468,'Stefan Szolc-Rogoziński');
INSERT INTO authors (AuthorId, Author) VALUES (469,'Joseph Conrad');
INSERT INTO authors (AuthorId, Author) VALUES (470,'Charles de Montesquieu (Monteskiusz)');
INSERT INTO authors (AuthorId, Author) VALUES (471,'Ajschylos');
INSERT INTO authors (AuthorId, Author) VALUES (472,'Charles Perrault');
SET IDENTITY_INSERT authors OFF 