use [Projekt_zespolowy];

SET IDENTITY_INSERT tags ON
INSERT INTO tags (TagId, Tag) VALUES (1,'Proza poetycka');
INSERT INTO tags (TagId, Tag) VALUES (2,'Kazanie');
INSERT INTO tags (TagId, Tag) VALUES (3,'Idylla');
INSERT INTO tags (TagId, Tag) VALUES (4,'Artykuł naukowy');
INSERT INTO tags (TagId, Tag) VALUES (5,'Dramat historyczny');
INSERT INTO tags (TagId, Tag) VALUES (6,'Ziemia Radomska');
INSERT INTO tags (TagId, Tag) VALUES (7,'Średniowiecze');
INSERT INTO tags (TagId, Tag) VALUES (8,'Kronika');
INSERT INTO tags (TagId, Tag) VALUES (9,'Puszcza Sandomierska');
INSERT INTO tags (TagId, Tag) VALUES (10,'Hymn');
INSERT INTO tags (TagId, Tag) VALUES (11,'Poemat heroikomiczny');
INSERT INTO tags (TagId, Tag) VALUES (12,'Dramat romantyczny');
INSERT INTO tags (TagId, Tag) VALUES (13,'Pamiętnik');
INSERT INTO tags (TagId, Tag) VALUES (14,'Powieść epistolarna');
INSERT INTO tags (TagId, Tag) VALUES (15,'Dramat współczesny');
INSERT INTO tags (TagId, Tag) VALUES (16,'Erotyk');
INSERT INTO tags (TagId, Tag) VALUES (17,'Esej');
INSERT INTO tags (TagId, Tag) VALUES (18,'Odezwa');
INSERT INTO tags (TagId, Tag) VALUES (19,'Poemat alegoryczny');
INSERT INTO tags (TagId, Tag) VALUES (20,'Ballada');
INSERT INTO tags (TagId, Tag) VALUES (21,'Epika');
INSERT INTO tags (TagId, Tag) VALUES (22,'Dramat niesceniczny');
INSERT INTO tags (TagId, Tag) VALUES (23,'Komediodramat');
INSERT INTO tags (TagId, Tag) VALUES (24,'Gawęda');
INSERT INTO tags (TagId, Tag) VALUES (25,'Komedia');
INSERT INTO tags (TagId, Tag) VALUES (26,'Epos rycerski');
INSERT INTO tags (TagId, Tag) VALUES (27,'Akt prawny');
INSERT INTO tags (TagId, Tag) VALUES (28,'Poemat');
INSERT INTO tags (TagId, Tag) VALUES (29,'Deutsch');
INSERT INTO tags (TagId, Tag) VALUES (30,'Poemat prozą');
INSERT INTO tags (TagId, Tag) VALUES (31,'français');
INSERT INTO tags (TagId, Tag) VALUES (32,'Oda');
INSERT INTO tags (TagId, Tag) VALUES (33,'Artykuł');
INSERT INTO tags (TagId, Tag) VALUES (34,'Dramat szekspirowski');
INSERT INTO tags (TagId, Tag) VALUES (35,'Gawęda szlachecka');
INSERT INTO tags (TagId, Tag) VALUES (36,'Legenda');
INSERT INTO tags (TagId, Tag) VALUES (37,'Rozprawa polityczna');
INSERT INTO tags (TagId, Tag) VALUES (38,'Pieśń');
INSERT INTO tags (TagId, Tag) VALUES (39,'Reportaż podróżniczy');
INSERT INTO tags (TagId, Tag) VALUES (40,'Aforyzm');
INSERT INTO tags (TagId, Tag) VALUES (41,'Biskupizna');
INSERT INTO tags (TagId, Tag) VALUES (42,'Humoreska');
INSERT INTO tags (TagId, Tag) VALUES (43,'Liryka');
INSERT INTO tags (TagId, Tag) VALUES (44,'Przypowieść');
INSERT INTO tags (TagId, Tag) VALUES (45,'Motto');
INSERT INTO tags (TagId, Tag) VALUES (46,'Rzeszowskie');
INSERT INTO tags (TagId, Tag) VALUES (47,'Tragedia');
INSERT INTO tags (TagId, Tag) VALUES (48,'Podhale');
INSERT INTO tags (TagId, Tag) VALUES (49,'Dwudziestolecie międzywojenne');
INSERT INTO tags (TagId, Tag) VALUES (50,'Poemat dygresyjny');
INSERT INTO tags (TagId, Tag) VALUES (51,'List');
INSERT INTO tags (TagId, Tag) VALUES (52,'Dramat antyczny');
INSERT INTO tags (TagId, Tag) VALUES (53,'Baśń');
INSERT INTO tags (TagId, Tag) VALUES (54,'Satyra');
INSERT INTO tags (TagId, Tag) VALUES (55,'Tren');
INSERT INTO tags (TagId, Tag) VALUES (56,'Felieton');
INSERT INTO tags (TagId, Tag) VALUES (57,'Dramat poetycki');
INSERT INTO tags (TagId, Tag) VALUES (58,'Renesans');
INSERT INTO tags (TagId, Tag) VALUES (59,'Wiersz sylabotoniczny');
INSERT INTO tags (TagId, Tag) VALUES (60,'Starożytność');
INSERT INTO tags (TagId, Tag) VALUES (61,'Modernizm');
INSERT INTO tags (TagId, Tag) VALUES (62,'Oświecenie');
INSERT INTO tags (TagId, Tag) VALUES (63,'lietuvių');
INSERT INTO tags (TagId, Tag) VALUES (64,'Dialog');
INSERT INTO tags (TagId, Tag) VALUES (65,'Rozprawa');
INSERT INTO tags (TagId, Tag) VALUES (66,'Bajka');
INSERT INTO tags (TagId, Tag) VALUES (67,'Wiersz');
INSERT INTO tags (TagId, Tag) VALUES (68,'Tragifarsa');
INSERT INTO tags (TagId, Tag) VALUES (69,'Dedykacja');
INSERT INTO tags (TagId, Tag) VALUES (70,'Ballada romantyczna');
INSERT INTO tags (TagId, Tag) VALUES (71,'Biografia');
INSERT INTO tags (TagId, Tag) VALUES (72,'Jasełka');
INSERT INTO tags (TagId, Tag) VALUES (73,'Współczesność');
INSERT INTO tags (TagId, Tag) VALUES (74,'Epopeja');
INSERT INTO tags (TagId, Tag) VALUES (75,'Dziennik');
INSERT INTO tags (TagId, Tag) VALUES (76,'Lament');
INSERT INTO tags (TagId, Tag) VALUES (77,'Sielanka');
INSERT INTO tags (TagId, Tag) VALUES (78,'Pogadanka');
INSERT INTO tags (TagId, Tag) VALUES (79,'Bajka ludowa');
INSERT INTO tags (TagId, Tag) VALUES (80,'Farsa');
INSERT INTO tags (TagId, Tag) VALUES (81,'English');
INSERT INTO tags (TagId, Tag) VALUES (82,'Powieść poetycka');
INSERT INTO tags (TagId, Tag) VALUES (83,'Psalm');
INSERT INTO tags (TagId, Tag) VALUES (84,'Epos');
INSERT INTO tags (TagId, Tag) VALUES (85,'Traktat');
INSERT INTO tags (TagId, Tag) VALUES (86,'Sonet');
INSERT INTO tags (TagId, Tag) VALUES (87,'Poradnik');
INSERT INTO tags (TagId, Tag) VALUES (88,'Romantyzm');
INSERT INTO tags (TagId, Tag) VALUES (89,'Publicystyka');
INSERT INTO tags (TagId, Tag) VALUES (90,'Melodramat');
INSERT INTO tags (TagId, Tag) VALUES (91,'Dramat wierszowany');
INSERT INTO tags (TagId, Tag) VALUES (92,'Opowiadanie');
INSERT INTO tags (TagId, Tag) VALUES (93,'Praca naukowa');
INSERT INTO tags (TagId, Tag) VALUES (94,'Nowela');
INSERT INTO tags (TagId, Tag) VALUES (95,'Epos satyryczny');
INSERT INTO tags (TagId, Tag) VALUES (96,'Odczyt');
INSERT INTO tags (TagId, Tag) VALUES (97,'Powiastka filozoficzna');
INSERT INTO tags (TagId, Tag) VALUES (98,'Pozytywizm');
INSERT INTO tags (TagId, Tag) VALUES (99,'Barok');
INSERT INTO tags (TagId, Tag) VALUES (100,'Manifest');
INSERT INTO tags (TagId, Tag) VALUES (101,'Różne');
INSERT INTO tags (TagId, Tag) VALUES (102,'Epigramat');
INSERT INTO tags (TagId, Tag) VALUES (103,'Reportaż');
INSERT INTO tags (TagId, Tag) VALUES (104,'Fraszka');
INSERT INTO tags (TagId, Tag) VALUES (105,'Dramat');
INSERT INTO tags (TagId, Tag) VALUES (106,'Powieść');
SET IDENTITY_INSERT tags OFF 